import { DoCheck, EventEmitter, IterableDiffers, OnChanges, SimpleChange } from '@angular/core';
import { BasicList } from './basic-list';
export declare type compareFunction = (a: any, b: any) => number;
export declare class DualListComponent implements DoCheck, OnChanges {
    private differs;
    static AVAILABLE_LIST_NAME: string;
    static CONFIRMED_LIST_NAME: string;
    static LTR: string;
    static RTL: string;
    static DEFAULT_FORMAT: {
        add: string;
        remove: string;
        all: string;
        none: string;
        direction: string;
    };
    key: string;
    display: string;
    height: string;
    filter: boolean;
    format: any;
    sort: boolean;
    compare: compareFunction;
    source: Array<any>;
    destination: Array<any>;
    editRight: boolean;
    editLeft: boolean;
    tooltipProperty: string;
    destinationChange: EventEmitter<{}>;
    editItem: EventEmitter<{}>;
    available: BasicList;
    confirmed: BasicList;
    sourceDiffer: any;
    destinationDiffer: any;
    private sorter;
    constructor(differs: IterableDiffers);
    ngOnChanges(changeRecord: {
        [key: string]: SimpleChange;
    }): void;
    ngDoCheck(): void;
    buildAvailable(source: Array<any>): boolean;
    buildConfirmed(destination: Array<any>): boolean;
    updatedSource(): void;
    updatedDestination(): void;
    direction(): boolean;
    dragEnd(list?: BasicList): boolean;
    drag(event: DragEvent, item: any, list: BasicList): void;
    allowDrop(event: DragEvent, list: BasicList): boolean;
    dragLeave(): void;
    drop(event: DragEvent, list: BasicList): void;
    private trueUp();
    findItemIndex(list: Array<any>, item: any, key?: any): number;
    private makeUnavailable(source, item);
    moveItem(source: BasicList, target: BasicList, item?: any): void;
    isItemSelected(list: Array<any>, item: any): boolean;
    shiftClick(event: MouseEvent, index: number, source: BasicList, item: any): void;
    selectItem(list: Array<any>, item: any): void;
    selectAll(source: BasicList): void;
    selectNone(source: BasicList): void;
    isAllSelected(source: BasicList): boolean;
    isAnySelected(source: BasicList): boolean;
    onEditItem(item: any): void;
    private unpick(source);
    clearFilter(source: BasicList): void;
    onFilter(source: BasicList): void;
    private makeId(item);
    private makeName(item);
}
